### ISSUE TITLE
Not working, all permissions false

### ISSUE THREAD

**Issue by FuriousLeech** [Blumlaut/EasyAdmin#169]
I'm not too familiar with this, but i know its got to be working. i did your troubleshoot where i add debug where it'll print out my permissions, and it says all false. I cannot open easyadmin. I'm using my steam identifier so idk whats wrong.

**Comment by Blumlaut** [comment]
In most cases you have configured your permissions incorrectly, i would recommend joining our Support Discord, and then upload your `server.cfg` file into the #support-ea channel, a bot will take a look at your config and find possible mistakes, otherwise if you dont want to join it, feel free to post your Permissions section as a reply here.
