### ISSUE TITLE
suggestion 

### ISSUE THREAD

**Issue by majdi09sh** [Blumlaut/EasyAdmin#326]
can you add if someone calladmin and press like this f5 will teleport to admin ?
can you add arabic language

**Comment by Blumlaut** [comment]
Hey, 
> can you add if someone calladmin and press like this f5 will teleport to admin ?
Can you describe this one further? Do you want so reporting players can teleport to admins on their own? Admins can already teleport players (click on the "Reporter" option and teleport)

>  can you add arabic language
Translations are provided by the Community, if you think you are capable of translating EasyAdmin please take a look here:
https://easyadmin.readthedocs.io/en/latest/translating/

AFAIK Arabic may not work due to the characters not actually being in the GTA V Fontset.
