### ISSUE TITLE
Stop printing the outdated easyadmin messages so often and lengthy

### ISSUE THREAD

**Issue by mcNuggets1** [Blumlaut/EasyAdmin#383]
As EasyAdmin is updated like twice a day for some unknown reasons, I suggest to adjust the outdated message, so it takes either less space in the console or stop it from being repeated, bloating the console in the long run, especially when testing.

**Comment by Blumlaut** [comment]
> As EasyAdmin is updated like twice a day for some unknown reasons,
changelogs exist? currently updates are rather high traffic because the discord bot feature is in active development and new issues are found and fixed frequently, its either this, or long update cycles á la discord.js, where important patches take actual _years_ to be added to a release, which is an issue we are currently facing while developing the bot, as we cannot use the official latest version due to a bug fix which didnt make it into a release, which has been pending a new release for over a year now.

> I suggest to adjust the outdated message
> bloating the console in the long run
thats the point, people should update when we tell them to

quick look at telemetry reveals that a vast majority of people run outdated easyadmin versions, the _most popular_ version right now is a version from mid 2021, which is not only utterly outdated but is missing some major patches.

You should keep your resources up to date, especially when its something as server-critical as an admin panel.

Also, the message used to be _even longer_, how about that?

**Comment by mcNuggets1** [comment]
I've been updating EasyAdmin like 10 times the last weeks.
I keep my resources updated, and that's why I'm getting annoyed, which should be reasonable.
But okay, I will just git pull new versions once a month now. Have a fine day anyways.

**Comment by Blumlaut** [comment]
> But okay, I will just git pull new versions once a month now

or just automate it?

```bash
your_easyadmin_path=~/home/fxserver/server-data/resources/EasyAdmin
cd $your_easyadmin_path

dl=$(curl -sSL https://api.github.com/repos/Blumlaut/EasyAdmin/releases/latest | jq -r .zipball_url )

wget $dl -O easyadmin.zip
unzip -o easyadmin.zip && rm easyadmin.zip
cp -Rfv *Blumlaut-EasyAdmin*/* .
rm -rf *Blumlaut-EasyAdmin*
```
